version: '3'

services:
  app:
    build: .
    container_name: iniciando-django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/home/django/app
    ports:
    - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: iniciando-django-db
    tty: true
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
    - django-pgdata:/var/lib/postgresql/data

volumes:
  django-pgdata:
    external: true
